[package]
name = "svfmt-cli"
version = "0.1.0"
authors = ["Rob Donnelly <rfdonnelly@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "svfmt",
]

[[bin]]
name = "svfmt"
path = "src/main.rs"

[dependencies]
env_logger = "0.6.2"
svfmt = { path = "svfmt" }
snafu = "0.4"
