[package]
name = "svfmt"
version = "0.1.0"
authors = ["Rob Donnelly <rfdonnelly@gmail.com>"]
edition = "2018"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
env_logger = "0.6.2"
indoc = "0.3"
pretty_assertions = "0.6"

[dependencies]
log = "0.4.0"
tree-sitter = "0.3"
snafu = "0.4"
